### 一、基础创建与查看
1. 导入 pandas，用字典创建 DataFrame：

   name: Tom, Jerry, Mike
   score: 85, 92, 78
   gender: 男，女，男

2. 查看上述 DataFrame 的前 1 行、形状、列名、数据类型。

3. 用列表创建 DataFrame：

   data = [[1, "A"], [2, "B"], [3, "C"]]

   列名设为 id、tag

In [ ]:
#1
import pandas as pd

data = {
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78],
    'gender': ['男', '女', '男']
}
aa=pd.DataFrame(data)
aa

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [38]:
#2
a1=aa.head(1)
a2=aa.shape
a3=aa.columns.tolist()
a4=aa.dtypes
print(a1)
print(a2)
print(a3)
print(a4)

  name  score gender
0  Tom     85      男
(3, 3)
['name', 'score', 'gender']
name      object
score      int64
gender    object
dtype: object

In [ ]:
#3
data=[[1, "A"], [2, "B"], [3, "C"]]
pd.DataFrame(data2, columns=['id', 'tag'])

   id tag
0   1   A
1   2   B
2   3   C

### 二、列与行操作

1. 选取 score 和 gender 两列。
2. 选取索引 0、2 的行。
3. 筛选 score>80 的行。
4. 新增一列 grade：score≥90 为优秀，否则为良好。
5. 删除 gender 列。

In [ ]:
#1
aa[['score', 'gender']]

   score gender
0     85      男
1     92      女
2     78      男

In [41]:
#2
aa.loc[[0, 2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

In [42]:
#3
aa[aa['score']>80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

In [43]:
#4
aa['grade'] = aa['score'].apply(lambda x:'优秀' if x>=90 else'良好')
aa

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

In [44]:
#5
aa.drop('gender', axis=1)

    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

### 三、缺失值

1. 创建含缺失值的 DataFrame：
   data = {"x":[1, None, 3], "y":[None, 5, 6]}
   检测缺失值并统计每列缺失数量。

2. 用 0 填充缺失值；删除含缺失值的行。

In [ ]:
#1
data3={"x": [1, None, 3], "y": [None, 5, 6]}
bb=pd.DataFrame(data3)
bb

     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

In [ ]:
bb.isnull()#缺失位置为true

       x      y
0  False   True
1   True  False
2  False  False

In [ ]:
bb.isnull().sum()

x    1
y    1
dtype: int64

In [ ]:
#2
bb.fillna(0)

     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

In [ ]:
bb.dropna()

     x    y
2  3.0  6.0

### 四、分组聚合

1. 按 gender 分组，求 score 的均值和最大值。
2. 按 gender 分组，统计每组人数。

In [53]:
data = {
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78],
    'gender': ['男', '女', '男']
}
aa=pd.DataFrame(data)
aa

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [54]:
#1
aa.groupby('gender')['score'].agg(['mean','max'])

        mean  max
gender
女       92.0   92
男       81.5   85

In [55]:
#2
aa.groupby('gender').size()

gender
女    1
男    2
dtype: int64

### 五、排序与去重

1. 按 score 升序排序。
2. 给 DataFrame 添加一行重复数据（如 Tom,85, 男），去重。

In [56]:
#1
aa.sort_values(by='score', ascending=True)

    name  score gender
2   Mike     78      男
0    Tom     85      男
1  Jerry     92      女

In [ ]:
#2

aa = pd.concat([aa, pd.DataFrame([['Tom',85,'男']], columns=aa.columns)], ignore_index=True)
print(aa)

bb=aa.drop_duplicates()
print(bb)

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男
3    Tom     85      男
    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

### 六、合并与拼接

1. 横向合并：

   df1 = pd.DataFrame ({"id":[1,2], "name":["X","Y"]})
   df2 = pd.DataFrame ({"id":[1,2], "age":[20,30]})

   按 id 合并。   

2. 纵向拼接：

   df_a = pd.DataFrame ({"val":[1,2]})

   df_b = pd.DataFrame ({"val":[3,4]})

   拼接后重置索引。

In [ ]:
#1
df1 = pd.DataFrame({"id": [1, 2], "name": ["X", "Y"]})
df2 = pd.DataFrame({"id": [1, 2], "age": [20, 30]})
print(df1)
print(df2)

   id name
0   1    X
1   2    Y
   id  age
0   1   20
1   2   30

In [59]:
#横向合并
df3= pd.merge(df1, df2, on="id")
df3

   id name  age
0   1    X   20
1   2    Y   30

In [60]:
#2
df_a = pd.DataFrame ({"val":[1,2]})
df_b = pd.DataFrame ({"val":[3,4]})

df4= pd.concat([df_a, df_b], ignore_index=True)
df4

   val
0    1
1    2
2    3
3    4

### 七、时间处理

1. 创建时间列：["2025-01-01","2025-01-02","2025-01-03"]，转为 datetime 格式。
2. 提取时间列的月份、星期。

In [ ]:
#1
time=pd.DataFrame({"date": ["2025-01-01", "2025-01-02", "2025-01-03"]})
time['date'] = pd.to_datetime(time['date'])
time

        date
0 2025-01-01
1 2025-01-02
2 2025-01-03

In [ ]:
#2
time['month'] = time['date'].dt.month
time['weekday'] = time['date'].dt.weekday
time

        date  month  weekday
0 2025-01-01      1        2
1 2025-01-02      1        3
2 2025-01-03      1        4

### 八、高级操作

1. 对 score 列做标准化（(值 - 均值)/ 标准差）。
2. 用透视表：行是 gender，值是 score，聚合函数为中位数。

In [64]:
#1
bb['score_std'] = (bb['score'] - bb['score'].mean()) / bb['score'].std()
bb

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19404\1369770551.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb['score_std'] = (bb['score'] - bb['score'].mean()) / bb['score'].std()

    name  score gender  score_std
0    Tom     85      男        0.0
1  Jerry     92      女        1.0
2   Mike     78      男       -1.0

In [65]:
#2
pd.pivot_table(bb, index='gender', values='score', aggfunc='median')

        score
gender
女        92.0
男        81.5